[package]
name = "wasmbuild"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[dependencies]
anyhow = "1.0.57"
js-sys = "0.3.60"
serde = { version = "1.0.130", features = ["derive", "rc"] }
# make sure to update the version in lib/versions.ts to match this version
wasm-bindgen = "0.2.83"
wasm-bindgen-cli-support = "0.2.83"
serde-wasm-bindgen = "0.4.3"
